version: '3'
services:
   47-productpage:
    image: 47/productpage
    build: ./bookinfo/src/productpage/.
    ports:
      - "9080:9080"
    environment:
     - GROUP_NUMBER:'${group_number:-47}'
   47-ratings:
    image: 47/ratings
    build: ./bookinfo/src/ratings/.
    environment:
     - ENABLE_EXTERNAL_BOOK_SERVICE:'${enable_external_book_service:-true}'
     - SERVICE_VERSION:'${service_version:-v1}'
    expose:
      - "9080"
   47-reviews:
    image: 47/reviews-v1
    build: ./bookinfo/src/reviews/reviews-wlpcfg/.
    environment:
     - ENABLE_RATINGS:'${enable_ratings:-true}'
    expose:
      - "9080"
   47-details:
    image: 47/details
    build: ./bookinfo/src/details/.
    environment:
     - SERVICE_VERSION:'${service_version:-v1}'
    expose:
      - "9080"
