version: '3'
services:
   47-productpage:
    image: 47/productpage
    build: ./bookinfo/src/productpage/.
    ports:
      - "9080"
    environment:
     - GROUP_NUMBER=47
   47-ratings:
    image: 47/ratings
    build: ./bookinfo/src/ratings/.
    environment:
     - ENABLE_EXTERNAL_BOOK_SERVICE=true
     - SERVICE_VERSION=v1
    ports:
      - "9080"
   47-reviews:
    image: 47/reviews-v1
    build: ./bookinfo/src/reviews/reviews-wlpcfg/.
    environment:
     - ENABLE_RATINGS=true
    ports:
      - "9080"
   47-details:
    image: 47/details
    build: ./bookinfo/src/details/.
    environment:
     - SERVICE_VERSION=v1 
    ports:
      - "9080"
