version: '3'
services:
   47-productpage:
    build: ./bookinfo/src/productpage/.
    image: 47/productpage
    container_name: 47-productpage
    volumes:
      - 47-app:/var/lib/productpage
    environment:
      - GROUP_NUMBER=47
    ports:
      - "9050:9080"
   47-details:
    build: ./bookinfo/src/details/.
    image: 47/details
    container_name: 47-details
    volumes:
      - 47-app:/var/lib/details
    environment:
      - SERVICE_VERSION=v1 
    ports:
      - "9050:9080"
   47-reviews:
    build: ./bookinfo/src/reviews/reviews-wlpcfg/.
    image: 47/reviews-v1
    container_name: 47-reviews
    volumes:
      - 47-app:/var/lib/reviews
    environment:
      - ENABLE_RATINGS=true
    ports:
      - "9050:9080"
   47-ratings:
    build: ./bookinfo/src/ratings/.
    image: 47/ratings
    container_name: 47-ratings
    volumes:
      - 47-app:/var/lib/ratings
    environment:
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
      - SERVICE_VERSION=v1
    ports:
      - "9050:9080"
volumes:
  47-app:
